/**
 * pdf-index.mjs — shared writer for data/pdf-index.tsv.
 *
 * Both generate-pdf.mjs (autogenerated CVs) and register-pdf.mjs (manually
 * supplied CV variants) need to record a report# → PDF mapping in the same
 * file, with the same replace-on-report/replace-on-path semantics. Splitting
 * this out avoids two independent writers drifting on schema or on the
 * dedup/replace rule.
 *
 * Columns: report \t pdf \t html \t format \t date \t source \t source_doc
 * - `source`: 'generated' (default, written by generate-pdf.mjs) or 'manual'
 *   (written by register-pdf.mjs for a candidate-supplied variant).
 * - `source_doc`: repo-relative path to a non-HTML editable source (e.g. a
 *   .docx a manual variant was exported from) — blank for generated rows,
 *   which use `html` for that purpose instead.
 * Trailing columns only — never insert mid-row, so older 5-column rows and
 * any reader indexing by position stay valid (same convention as
 * data/scan-history.tsv).
 */

import { resolve, dirname, relative, sep, isAbsolute } from 'path';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// CAREER_OPS_PDF_INDEX already existed as a read-side override (see
// sync-pdf-flags.mjs) before this module did — wiring it into the writer too
// closes that gap and makes both generate-pdf.mjs and register-pdf.mjs safe
// to point at a scratch file in tests instead of the real repo data.
export const PDF_INDEX_PATH = process.env.CAREER_OPS_PDF_INDEX
  ? resolve(process.env.CAREER_OPS_PDF_INDEX)
  : resolve(__dirname, 'data', 'pdf-index.tsv');
export const PDF_INDEX_HEADER =
  '# report\tpdf\thtml\tformat\tdate\tsource\tsource_doc — generated rows written by generate-pdf.mjs, manual rows by register-pdf.mjs, do not hand-edit\n';

/**
 * Convert a path to a repo-relative manifest entry, or blank if it is unknown
 * or outside the career-ops repository.
 *
 * @param {string} pathValue - Absolute or cwd-relative filesystem path.
 * @returns {string} Repo-relative path using forward slashes, or an empty string.
 */
export function repoRelativeManifestPath(pathValue) {
  if (!pathValue) return '';
  const rel = relative(__dirname, resolve(pathValue));
  if (rel === '' || rel.startsWith('..') || isAbsolute(rel)) return '';
  return rel.split(sep).join('/');
}

// "008" and "8" are the same report — zero-padded report-link form vs
// unpadded tracker-# form. Normalize so replacement rows match.
function normReportKey(s) {
  return (s || '').trim().replace(/^0+(?=\d)/, '');
}

/**
 * Record a PDF (generated or manually supplied) in data/pdf-index.tsv so
 * tools can map a tracker report number to the exact PDF.
 *
 * Replaces any existing row for the same PDF path, and — when a report
 * number is given — any existing row for that report number too (a new CV,
 * generated or manual, supersedes the prior one for that application).
 *
 * @param {string} reportNum
 * @param {string} pdfPath - Absolute or cwd-relative path to the PDF.
 * @param {string} htmlPath - Absolute or cwd-relative path to the source HTML, or '' if none.
 * @param {string} format - 'letter' | 'a4'.
 * @param {{source?: 'generated'|'manual', sourceDoc?: string}} [opts]
 * @returns {string} The repo-relative PDF path written.
 */
export function updatePDFManifest(reportNum, pdfPath, htmlPath, format, opts = {}) {
  const { source = 'generated', sourceDoc = '' } = opts;
  const relPDF = relative(__dirname, pdfPath).split(sep).join('/');
  const relHTML = repoRelativeManifestPath(htmlPath);
  const relSourceDoc = repoRelativeManifestPath(sourceDoc);
  const date = new Date().toISOString().slice(0, 10);

  let lines = [];
  if (existsSync(PDF_INDEX_PATH)) {
    lines = readFileSync(PDF_INDEX_PATH, 'utf-8').split('\n').filter((line) => {
      if (!line.trim() || line.startsWith('#')) return false;
      const fields = line.split('\t');
      if (fields[1] === relPDF) return false;
      if (reportNum && normReportKey(fields[0]) === normReportKey(reportNum)) return false;
      return true;
    });
  }

  lines.push([reportNum || '', relPDF, relHTML, format, date, source, relSourceDoc].join('\t'));

  mkdirSync(dirname(PDF_INDEX_PATH), { recursive: true });
  writeFileSync(PDF_INDEX_PATH, PDF_INDEX_HEADER + lines.join('\n') + '\n');
  return relPDF;
}
