#!/usr/bin/env node
/**
 * register-pdf.mjs — register a candidate-supplied CV variant into
 * data/pdf-index.tsv, the same file generate-pdf.mjs writes for
 * autogenerated CVs.
 *
 * WHY: pdf-index.tsv is how the rest of career-ops answers "which CV went
 * with this application" — the `email` mode's attachment lookup, the
 * dashboard, `find.mjs`. A manually tailored CV (hand-written, or exported
 * from a Word doc) is invisible to all of that unless it's registered the
 * same way. This script is the manual counterpart to generate-pdf.mjs's own
 * (now-shared, see pdf-index.mjs) manifest write.
 *
 * Copies the given PDF — and, optionally, its editable source (e.g. a
 * .docx) — into output/ using the same cv-{candidate}-{company} naming
 * convention as autogenerated CVs, with a "-manual" segment so it's never
 * confused with, or silently overwritten by, a future autogenerated CV for
 * the same report. Then records report#, PDF path, format, and source in
 * pdf-index.tsv (source: 'manual') via the shared writer in pdf-index.mjs.
 *
 * Usage:
 *   node register-pdf.mjs <report#|tracker#|company> <pdfPath> [--doc <path>] [--format letter|a4] [--date YYYY-MM-DD] [--json]
 *
 * <report#|tracker#|company> resolves the same way find.mjs does — a
 * numeric report/tracker number, or a company/role text fragment — so
 * "register the CV I used for Canva" works without needing the exact
 * report number.
 *
 * Exit codes:
 *   0 success
 *   1 usage error (missing/invalid args, unknown flag, source file missing)
 *   2 tracker row not found, or ambiguous (multiple matches)
 */

import { readFileSync, existsSync, copyFileSync, mkdirSync } from 'fs';
import { resolve, dirname, extname, join, relative } from 'path';
import { fileURLToPath } from 'url';
import yaml from 'js-yaml';
import { parseTrackerRows, findMatches } from './find.mjs';
import { resolveTrackerPath } from './tracker-utils.mjs';
import { updatePDFManifest } from './pdf-index.mjs';

const CAREER_OPS = dirname(fileURLToPath(import.meta.url));

class RegisterError extends Error {
  constructor(code, message) {
    super(message);
    this.name = 'RegisterError';
    this.code = code;
  }
}

function todayStr() {
  return new Date().toISOString().slice(0, 10);
}

function isValidCalendarDate(str) {
  if (typeof str !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(str)) return false;
  const d = new Date(str);
  return !isNaN(d) && d.toISOString().slice(0, 10) === str;
}

/** Lowercase, hyphenate — same convention as report-slug/company-slug elsewhere in career-ops. */
export function slugify(value) {
  return String(value || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'unknown';
}

/**
 * Resolve a candidate's full name from config/profile.yml into the
 * kebab-case {candidate} slug used in output/ filenames (mirrors modes/pdf.md
 * Step 15). Falls back to 'candidate' if the profile or field is absent.
 */
export function resolveCandidateSlug(profilePath) {
  if (!existsSync(profilePath)) return 'candidate';
  try {
    const profile = yaml.load(readFileSync(profilePath, 'utf-8'));
    const name = profile?.candidate?.full_name;
    return name ? slugify(name) : 'candidate';
  } catch {
    return 'candidate';
  }
}

/**
 * Resolve <report#|tracker#|company> against the tracker the same way
 * find.mjs does. Throws RegisterError('ROW_NOT_FOUND') for zero matches,
 * RegisterError('AMBIGUOUS') for 2+.
 *
 * @param {string} query
 * @param {string} trackerPath
 * @returns {{trackerNum:number, company:string, role:string, reportNum:string|null}}
 */
export function resolveRow(query, trackerPath) {
  if (!existsSync(trackerPath)) {
    throw new RegisterError('ROW_NOT_FOUND', `Tracker not found at ${trackerPath}`);
  }
  const rows = parseTrackerRows(readFileSync(trackerPath, 'utf-8'));
  const hits = findMatches(rows, query);
  if (hits.length === 0) {
    throw new RegisterError('ROW_NOT_FOUND', `No tracker row matches "${query}"`);
  }
  if (hits.length > 1) {
    const list = hits.map(h => `#${h.trackerNum} ${h.company} — ${h.role}`).join('; ');
    throw new RegisterError('AMBIGUOUS', `"${query}" matches ${hits.length} rows — be more specific: ${list}`);
  }
  return hits[0];
}

/**
 * Copy the source PDF (and optional doc) into output/ with the
 * cv-{candidate}-{company}-manual-{date} naming convention, then record the
 * result in data/pdf-index.tsv with source: 'manual'.
 *
 * @param {object} opts
 * @param {string} opts.query - report#/tracker#/company fragment.
 * @param {string} opts.pdfPath - Path to the candidate-supplied PDF.
 * @param {string} [opts.docPath] - Path to an editable source (e.g. .docx), optional.
 * @param {string} [opts.format] - 'letter' | 'a4'. Default 'letter' per modes/_custom.md (US Letter for every CV).
 * @param {string} [opts.date] - YYYY-MM-DD, defaults to today.
 * @param {string} [opts.trackerPath]
 * @param {string} [opts.profilePath]
 * @returns {{trackerNum:number, reportNum:string|null, company:string, pdfPath:string, docPath:string|null}}
 */
export function registerManualPdf(opts) {
  const { query, pdfPath, docPath = null, format = 'letter' } = opts;
  const date = opts.date || todayStr();
  if (opts.date != null && !isValidCalendarDate(opts.date)) {
    throw new RegisterError('USAGE', `--date must be a real calendar date in YYYY-MM-DD form: ${opts.date}`);
  }
  if (!['letter', 'a4'].includes(format)) {
    throw new RegisterError('USAGE', `--format must be "letter" or "a4": ${format}`);
  }
  const absPdf = resolve(pdfPath);
  if (!existsSync(absPdf)) {
    throw new RegisterError('USAGE', `PDF not found: ${pdfPath}`);
  }
  const absDoc = docPath ? resolve(docPath) : null;
  if (absDoc && !existsSync(absDoc)) {
    throw new RegisterError('USAGE', `Doc not found: ${docPath}`);
  }

  const trackerPath = opts.trackerPath || resolveTrackerPath(CAREER_OPS);
  const row = resolveRow(query, trackerPath);

  const profilePath = opts.profilePath || join(CAREER_OPS, 'config', 'profile.yml');
  const candidateSlug = resolveCandidateSlug(profilePath);
  const companySlug = slugify(row.company);
  const baseName = `cv-${candidateSlug}-${companySlug}-manual-${date}`;

  // CAREER_OPS_OUTPUT_DIR override (mirrors CAREER_OPS_PDF_INDEX in
  // pdf-index.mjs) — lets tests point at a scratch dir instead of the real
  // output/, so a bad test run can't overwrite a candidate's real CV files.
  const outputDir = process.env.CAREER_OPS_OUTPUT_DIR
    ? resolve(process.env.CAREER_OPS_OUTPUT_DIR)
    : join(CAREER_OPS, 'output');
  mkdirSync(outputDir, { recursive: true });

  const destPdf = join(outputDir, `${baseName}.pdf`);
  copyFileSync(absPdf, destPdf);

  let destDoc = null;
  if (absDoc) {
    const ext = extname(absDoc) || '.docx';
    destDoc = join(outputDir, `${baseName}${ext}`);
    copyFileSync(absDoc, destDoc);
  }

  const relPdf = updatePDFManifest(row.reportNum || '', destPdf, '', format, {
    source: 'manual',
    sourceDoc: destDoc || '',
  });

  return {
    trackerNum: row.trackerNum,
    reportNum: row.reportNum,
    company: row.company,
    pdfPath: relPdf,
    docPath: destDoc ? relative(CAREER_OPS, destDoc).split('\\').join('/') : null,
  };
}

// --- CLI ---------------------------------------------------------------

function parseCliArgs(argv) {
  const opts = { format: 'letter', json: false, docPath: null, date: null };
  const positionals = [];
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--doc') {
      i++;
      if (argv[i] === undefined) throw new RegisterError('USAGE', '--doc requires a value');
      opts.docPath = argv[i];
    } else if (a === '--format') {
      i++;
      if (argv[i] === undefined) throw new RegisterError('USAGE', '--format requires a value');
      opts.format = argv[i];
    } else if (a === '--date') {
      i++;
      if (argv[i] === undefined) throw new RegisterError('USAGE', '--date requires a value');
      opts.date = argv[i];
    } else if (a === '--json') {
      opts.json = true;
    } else if (a.startsWith('--')) {
      throw new RegisterError('USAGE', `Unknown flag: ${a}`);
    } else {
      positionals.push(a);
    }
  }
  if (positionals.length !== 2) {
    throw new RegisterError(
      'USAGE',
      'Usage: node register-pdf.mjs <report#|tracker#|company> <pdfPath> [--doc <path>] [--format letter|a4] [--date YYYY-MM-DD] [--json]'
    );
  }
  opts.query = positionals[0];
  opts.pdfPath = positionals[1];
  return opts;
}

const EXIT_CODES = { USAGE: 1, ROW_NOT_FOUND: 2, AMBIGUOUS: 2 };

function main() {
  const argv = process.argv.slice(2);
  const jsonRequested = argv.includes('--json');
  let opts;
  try {
    opts = parseCliArgs(argv);
  } catch (err) {
    reportError(err, jsonRequested);
    return;
  }

  try {
    const result = registerManualPdf(opts);
    if (opts.json) {
      console.log(JSON.stringify({ ok: true, ...result }));
    } else {
      console.log(`✅ Registered manual CV for #${result.trackerNum} (${result.company}): ${result.pdfPath}`);
      if (result.docPath) console.log(`   Source doc: ${result.docPath}`);
      if (!result.reportNum) console.log('   Note: this tracker row has no linked report — recorded without a report#.');
    }
    process.exit(0);
  } catch (err) {
    reportError(err, opts.json);
  }
}

function reportError(err, json) {
  const code = err.code || 'ERROR';
  const exitCode = EXIT_CODES[code] ?? 1;
  if (json) console.log(JSON.stringify({ ok: false, error: err.message, code }));
  console.error(`❌ ${err.message}`);
  process.exit(exitCode);
}

if (process.argv[1] && import.meta.url === `file://${resolve(process.argv[1])}`) {
  main();
}
